name: Test and Deploy the Application 
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23

      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Install dependencies 
        run: npm install
        
      - name: Run test cases
        run: npm run check | tee test-results.txt

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results.txt
  deploy:
    runs-on: self-hosted
    needs: test
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Download the test results
        uses: actions/download-artifact@v4
        with:
          name: test-results

      - name: Display the test result
        run: cat test-results.txt

      - name: Install dependencies 
        run: npm install

      - name: Start the Application
        run: |
          pm2 delete node-app || true
          pm2 start "./src/server.js" --name node-app
          pm2 save
